/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIManager;

import java.awt.Cursor;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import RegistrationEngine.*;
import javax.swing.JButton;
/**
 *
 * @author acer
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    ArrayList<String> VIRUSES=new ArrayList<String>();
    private final JFrame j;
    private Thread thh;
    SystemTray sy;
    TrayIcon ti;
    javax.swing.ImageIcon ic2,ic;
    private boolean canMove=false;
        int initX;
    int initY;
    GSLib gs=new GSLib();
    LinksDataStructure lds=new LinksDataStructure();
    public UI() {
        j=this;
        int w=Toolkit.getDefaultToolkit().getScreenSize().width-350;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-200;
        this.setLocation(w, h);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fixbutton = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ll = new javax.swing.JLabel();
        drive = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalExclusionType(null);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fixbutton.setBackground(new java.awt.Color(0, 153, 0));
        fixbutton.setForeground(new java.awt.Color(255, 255, 255));
        fixbutton.setText("Fix ");
        fixbutton.setToolTipText("Fix ound Threats");
        fixbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        fixbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(fixbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 67, 25));

        stopBtn.setBackground(new java.awt.Color(255, 0, 0));
        stopBtn.setForeground(new java.awt.Color(255, 255, 255));
        stopBtn.setText("Stop");
        stopBtn.setToolTipText("Stop and close UI");
        stopBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });
        jPanel1.add(stopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 115, 73, 25));

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        ll.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ll.setForeground(new java.awt.Color(255, 255, 255));
        ll.setText("Links Antivirus Mini Scanner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        drive.setBackground(new java.awt.Color(51, 51, 51));
        drive.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        drive.setForeground(new java.awt.Color(51, 51, 51));
        drive.setText("Scanning USB DISK");
        jPanel1.add(drive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 310, 27));

        output.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        output.setForeground(new java.awt.Color(51, 51, 51));
        output.setText("Threats : 0");
        jPanel1.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 116, 27));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linksantivirusagent/loader.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 60));

        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("Scanning in progress");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_stopBtnActionPerformed

    private void fixbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixbuttonActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, "Threats Deleted Successfully");
//        this.dispose();
    }//GEN-LAST:event_fixbuttonActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        canMove=true;
        initX = evt.getXOnScreen() - this.getX();
        initY = evt.getYOnScreen() -this.getY();
        this.setCursor(Cursor.MOVE_CURSOR);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
        canMove=false;
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        if(canMove){

        this.setLocation(evt.getXOnScreen() - initX,evt.getYOnScreen() - initY);
        }
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drive;
    private javax.swing.JButton fixbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel ll;
    private javax.swing.JLabel output;
    private javax.swing.JButton stopBtn;
    // End of variables declaration//GEN-END:variables
     void setFoundDrive(String dr) {
    }

    void sendMessage(String virus_found) {

    }
    
    public void setMiniTitle(String m){
    ll.setText(m);
    }
    public void setDrive(String d){
        drive.setText(d);
    }
    public void setThreats(String g){
        output.setText(g);
   }
    public JButton getFixButton(){
        return fixbutton;
    }
    public JButton getStopButton(){
        return stopBtn;
    }
    public JFrame getFrame(){
        return this;
    }
}

